package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/CodeGeetha/graphql-demo/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, email string) (*model.User, error) {
	// Simulate saving a new user
	newUser := &model.User{
		ID:    "1", // You’d use a UUID or DB-generated ID
		Name:  name,
		Email: email,
	}

	// Example: Save to a slice or DB
	r.Resolver.Users = append(r.Resolver.Users, newUser)

	return newUser, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return []*model.User{
		{
			ID:    "1",
			Name:  "Alice",
			Email: "alice@example.com",
		},
		{
			ID:    "2",
			Name:  "Bob",
			Email: "bob@example.com",
		},
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return &model.User{
		ID:    id,
		Name:  "Test User",
		Email: "test@example.com",
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
